"""Event management API routes.

Provides access to the Switchtec firmware event notification system.
Events are generated by the switch firmware for conditions such as link
state changes, AER errors, hot-plug activity, and firmware-internal
diagnostics.  Events are bucketed into three scopes:

- **Global events** -- switch-wide conditions (e.g. over-temperature).
- **Partition events** -- scoped to the current partition.
- **PFF events** -- scoped to individual port function framework entries.

The wait endpoint uses a dedicated thread pool (4 threads) to avoid
exhausting FastAPI's default worker pool, since the underlying C library
call can block for up to 300 seconds.
"""

from __future__ import annotations

import asyncio
from concurrent.futures import ThreadPoolExecutor
from functools import partial

from fastapi import APIRouter, Path
from pydantic import BaseModel, Field

from serialcables_switchtec.api.dependencies import DEVICE_ID_PATTERN, get_device
from serialcables_switchtec.api.error_handlers import raise_on_error
from serialcables_switchtec.models.events import EventSummaryResult

router = APIRouter()

_event_wait_executor = ThreadPoolExecutor(max_workers=4, thread_name_prefix="event-wait")





class WaitEventRequest(BaseModel):
    timeout_ms: int = Field(default=-1, ge=-1, le=300000)


@router.get(
    "/{device_id}/events/summary",
    response_model=EventSummaryResult,
)
def get_event_summary(
    device_id: str = Path(pattern=DEVICE_ID_PATTERN),
) -> EventSummaryResult:
    """Retrieve a summary of all pending events across all scopes.

    Returns an ``EventSummaryResult`` with aggregate counts:

    - ``global_events`` -- number of pending switch-wide events.
    - ``partition_events`` -- number of pending partition-scoped events.
    - ``pff_events`` -- number of pending PFF-scoped events.
    - ``total_count`` -- sum of all pending events across every scope.

    This is a lightweight, non-blocking call suitable for periodic polling.

    Parameters:

    - ``device_id`` -- the identifier assigned when the device was opened.

    Error responses:

    - **404 Not Found** -- device not found.
    - **500 Internal Server Error** -- event summary query failed.
    """
    dev = get_device(device_id)
    try:
        mgr = dev.events
        return mgr.get_summary()
    except Exception as e:
        raise_on_error(e, "get_event_summary")


@router.post("/{device_id}/events/clear")
def clear_events(
    device_id: str = Path(pattern=DEVICE_ID_PATTERN),
) -> dict[str, str]:
    """Clear all pending events across global, partition, and PFF scopes.

    After this call, the event summary counters will all read zero until new
    events are generated by the firmware.

    Parameters:

    - ``device_id`` -- the identifier assigned when the device was opened.

    Response format::

        {"status": "cleared"}

    Error responses:

    - **404 Not Found** -- device not found.
    - **500 Internal Server Error** -- event clear command failed.
    """
    dev = get_device(device_id)
    try:
        mgr = dev.events
        mgr.clear_all()
        return {"status": "cleared"}
    except Exception as e:
        raise_on_error(e, "clear_events")


@router.post("/{device_id}/events/wait")
async def wait_for_event(
    device_id: str = Path(pattern=DEVICE_ID_PATTERN),
    request: WaitEventRequest = ...,
) -> dict[str, str]:
    """Block until the firmware signals that at least one event has occurred.

    This is an async endpoint that offloads the blocking wait to a dedicated
    thread pool (4 workers, separate from FastAPI's default pool) to avoid
    starving other requests during long waits.

    Request body fields:

    - ``timeout_ms`` -- maximum time to wait in milliseconds.
      - ``-1`` (default): wait indefinitely (up to OS/driver limits).
      - ``0``: return immediately (non-blocking poll).
      - ``1`` to ``300000``: wait up to this many milliseconds (max 5 min).

    When an event arrives before the timeout, the response is::

        {"status": "event_received"}

    If the timeout expires with no event, the firmware returns a timeout
    error which is surfaced as a 500.

    Parameters:

    - ``device_id`` -- the identifier assigned when the device was opened.

    Error responses:

    - **404 Not Found** -- device not found.
    - **422 Unprocessable Entity** -- ``timeout_ms`` out of range.
    - **500 Internal Server Error** -- wait failed or timed out.
    """
    dev = get_device(device_id)
    try:
        mgr = dev.events
        loop = asyncio.get_running_loop()
        await loop.run_in_executor(
            _event_wait_executor,
            partial(mgr.wait_for_event, timeout_ms=request.timeout_ms),
        )
        return {"status": "event_received"}
    except Exception as e:
        raise_on_error(e, "wait_for_event")
